# Generated by Django 5.0.3 on 2026-04-15 03:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProformaInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pi_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("client_name", models.CharField(max_length=200)),
                (
                    "client_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "client_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("client_address", models.TextField(blank=True, null=True)),
                ("order_date", models.DateField()),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("garment_type", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PRODUCTION", "In Production"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proforma Invoice",
                "verbose_name_plural": "Proforma Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanningSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buttons_required", models.PositiveIntegerField(default=0)),
                ("buttons_type", models.CharField(blank=True, max_length=100)),
                ("buttons_color", models.CharField(blank=True, max_length=50)),
                (
                    "thread_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("thread_color", models.CharField(blank=True, max_length=50)),
                ("thread_type", models.CharField(blank=True, max_length=100)),
                ("zippers_required", models.PositiveIntegerField(default=0)),
                ("zippers_size", models.CharField(blank=True, max_length=50)),
                ("zippers_color", models.CharField(blank=True, max_length=50)),
                (
                    "tapes_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("tapes_type", models.CharField(blank=True, max_length=100)),
                ("tapes_color", models.CharField(blank=True, max_length=50)),
                ("polybags_required", models.PositiveIntegerField(default=0)),
                ("polybags_size", models.CharField(blank=True, max_length=50)),
                (
                    "fabric_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fabric_type", models.CharField(blank=True, max_length=100)),
                ("fabric_color", models.CharField(blank=True, max_length=50)),
                ("labels_required", models.PositiveIntegerField(default=0)),
                ("labels_type", models.CharField(blank=True, max_length=100)),
                ("other_materials", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_sheet",
                        to="orders.proformainvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planning Sheet",
                "verbose_name_plural": "Planning Sheets",
            },
        ),
    ]
