# Generated by Django 5.0.3 on 2026-04-16 10:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Intent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indent_number",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                (
                    "buyer_po_reference",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("intent_date", models.DateField()),
                (
                    "garment_sheet_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. style / sheet tab name (Waterproof Trousers)",
                        max_length=200,
                    ),
                ),
                ("item_description", models.TextField(blank=True)),
                ("total_garment_qty", models.PositiveIntegerField(default=0)),
                (
                    "size_breakdown",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of rows: color, per-size qty, totals (see PI/indent templates)",
                    ),
                ),
                ("packing_notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "prepared_by",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "received_by",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intents",
                        to="orders.proformainvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent (Indent)",
                "verbose_name_plural": "Intents (Indents)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="intent_attachments/%Y/%m/")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="orders.intent",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="IntentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField(default=1)),
                ("material_description", models.CharField(max_length=500)),
                ("variant", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "consumption_per_unit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "unit",
                    models.CharField(
                        default="PCS", help_text="MTRS, PCS, CONE, etc.", max_length=20
                    ),
                ),
                (
                    "total_required",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.intent",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to store SKU when raising POs",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intent_lines",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["intent", "line_number"],
                "unique_together": {("intent", "line_number")},
            },
        ),
    ]
