# Generated by Django 5.0.3 on 2026-04-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0002_intent_intentattachment_intentline"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="International customer record (optional; client fields may still be edited)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proforma_invoices",
                to="customers.customer",
            ),
        ),
    ]
