# Generated by Django 5.0.3 on 2026-04-16 13:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


def backfill_pi_lines(apps, schema_editor):
    ProformaInvoice = apps.get_model('orders', 'ProformaInvoice')
    ProformaInvoiceLine = apps.get_model('orders', 'ProformaInvoiceLine')
    for pi in ProformaInvoice.objects.all():
        if ProformaInvoiceLine.objects.filter(pi_id=pi.pk).exists():
            continue
        name = (pi.garment_type or '').strip() or 'Line item'
        qty = int(pi.quantity or 0)
        unit = pi.unit_price
        total = pi.total_amount
        if total is None and unit is not None and qty:
            total = (Decimal(str(qty)) * unit).quantize(Decimal('0.01'))
        ProformaInvoiceLine.objects.create(
            pi_id=pi.pk,
            line_number=1,
            item_name=name[:300],
            material='',
            color='',
            size_breakdown=[],
            quantity_pcs=qty,
            unit_price_usd=unit,
            line_value_usd=total,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0003_proformainvoice_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="buyer_po_number",
            field=models.CharField(
                blank=True, default="", help_text="Buyer's PO reference", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer master record — TO block on PI; client_* synced from here when set.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proforma_invoices",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="garment_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Summary of line items for lists/reports",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total pieces across PI lines",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="ProformaInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField(default=1)),
                (
                    "item_name",
                    models.CharField(help_text="Garment / style name", max_length=300),
                ),
                (
                    "material",
                    models.TextField(
                        blank=True, default="", help_text="e.g. fabric composition"
                    ),
                ),
                ("color", models.CharField(blank=True, default="", max_length=120)),
                (
                    "size_breakdown",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"size": "M", "qty": 450}, ...] — optional; qty pcs can be entered directly',
                    ),
                ),
                (
                    "quantity_pcs",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "line_value_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.proformainvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["pi", "line_number"],
                "unique_together": {("pi", "line_number")},
            },
        ),
        migrations.RunPython(backfill_pi_lines, noop_reverse),
    ]
