# Generated by Django 5.0.3 on 2026-04-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_pi_lines_and_buyer_po"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="buyer_signatory_for",
            field=models.CharField(
                blank=True, default="J B INTERNATIONAL", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="date_of_dispatch_display",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. 20TH FEBRUARY 2026 (EX-FACTORY DATE) — shown after DATE OF DISPATCH",
                max_length=400,
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="intermediary_bank_details",
            field=models.TextField(
                blank=True, default="", help_text="INTERMEDIARY BANK block on PI"
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="our_bank_details",
            field=models.TextField(
                blank=True, default="", help_text="OUR BANK block on PI"
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="payment_terms_display",
            field=models.TextField(
                blank=True,
                default="",
                help_text="e.g. 20% ADVANCE, REMAINING 80% AGAINST SHIPMENT DOCUMENTS",
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="port_of_discharge",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="return_email_instruction",
            field=models.CharField(
                blank=True,
                default="shivangi.jain@jbinternational.co.in",
                help_text="E-mail for seal & sign return instruction",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="seller_signatory_for",
            field=models.CharField(
                blank=True, default="CID TRADING LTD", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="proformainvoiceline",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Narrative description for PI (shown with size breakdown)",
            ),
        ),
    ]
