# Generated by Django 5.0.3 on 2026-04-22 15:53

import django.db.models.deletion
from django.db import migrations, models


def backfill_sheets(apps, schema_editor):
    Intent = apps.get_model("orders", "Intent")
    IntentSheet = apps.get_model("orders", "IntentSheet")
    IntentLine = apps.get_model("orders", "IntentLine")

    for intent in Intent.objects.all():
        sheet = IntentSheet.objects.create(
            intent_id=intent.id,
            label=(intent.garment_sheet_name or "")[:200] or "Sheet 1",
            sort_order=0,
            item_description=intent.item_description or "",
            size_breakdown=intent.size_breakdown or [],
            total_garment_qty=intent.total_garment_qty or 0,
        )
        IntentLine.objects.filter(intent_id=intent.id).update(sheet_id=sheet.id, intent_id=intent.id)


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_pi_trade_terms_and_line_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intentline",
            options={"ordering": ["sheet", "line_number"]},
        ),
        migrations.CreateModel(
            name="IntentSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Excel tab / sheet name, e.g. Waterproof Trousers",
                        max_length=200,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("item_description", models.TextField(blank=True, default="")),
                (
                    "size_breakdown",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of colour rows, per-size qty, totals (same format as one PI sheet in Excel).",
                    ),
                ),
                ("total_garment_qty", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheets",
                        to="orders.intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent sheet (Excel tab)",
                "ordering": ["intent", "sort_order", "id"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="intentline",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="intentline",
            name="sheet",
            field=models.ForeignKey(
                blank=True,
                help_text="BOM line belongs to one sheet (Excel tab).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="orders.intentsheet",
            ),
        ),
        migrations.RunPython(backfill_sheets, backwards_noop),
        migrations.AlterField(
            model_name="intentline",
            name="sheet",
            field=models.ForeignKey(
                help_text="BOM line belongs to one sheet (Excel tab).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="orders.intentsheet",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intentline",
            unique_together={("sheet", "line_number")},
        ),
    ]
