# Generated by Django 5.0.3 on 2026-06-15 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_buyerpo_buyerpo_lines"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerpoline",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discount % (0–100)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="buyerpoline",
            name="uom",
            field=models.CharField(
                blank=True,
                default="PCS",
                help_text="Unit of measure, e.g. PCS, DZ",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="buyerpo",
            name="buyer_contact",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Mr. Himanshu Banka",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="buyerpo",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. THROUGH CARRIER - BY SEA",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="buyerpo",
            name="delivery_terms",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. FOB-FREE ON BOARD",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="buyerpo",
            name="payment_terms",
            field=models.TextField(
                blank=True, default="", help_text="e.g. 60 DAYS FROM B/L DATE, D/A"
            ),
        ),
        migrations.AlterField(
            model_name="buyerpo",
            name="pi",
            field=models.ForeignKey(
                blank=True,
                help_text="Our internal PI linked to this buyer PO",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buyer_pos",
                to="orders.proformainvoice",
            ),
        ),
        migrations.AlterField(
            model_name="buyerpo",
            name="supplier_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Buyer's supplier code for us",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="buyerpoline",
            name="customer_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="OdL No / buyer line ref",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="buyerpoline",
            name="fabric",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. 65% polyester/35% cotton 245gr./sqm",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="buyerpoline",
            name="item_code",
            field=models.CharField(
                blank=True, default="", help_text="e.g. V181-0-02A", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="buyerpoline",
            name="item_name",
            field=models.CharField(help_text='e.g. TROUSERS "RABAT"', max_length=300),
        ),
        migrations.AlterField(
            model_name="buyerpoline",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="Total pieces (auto-sum from sizes or manual)"
            ),
        ),
        migrations.AlterField(
            model_name="buyerpoline",
            name="size_breakdown",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"size": "S", "qty": 350}, ...] — flexible sizes per party',
            ),
        ),
    ]
