# Generated by Django 5.0.3 on 2026-06-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_buyerpoline_uom_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerpo",
            name="po_document",
            field=models.FileField(
                blank=True,
                help_text="Scanned/original PO file from buyer",
                null=True,
                upload_to="buyer_po_docs/",
            ),
        ),
    ]
