# Generated by Django 5.0.3 on 2026-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_buyerpo_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerpo",
            name="pi_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="PI reference number generated from this PO, e.g. JBI/26-27/11",
                max_length=80,
            ),
        ),
    ]
