# Generated by Django 5.0.3 on 2026-06-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_pi_ref_on_buyer_po"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="inco_terms",
            field=models.CharField(
                blank=True, default="", help_text="e.g. FOB NHAVA SHEVA", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="port_of_loading",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. NHAVA SHEVA PORT",
                max_length=400,
            ),
        ),
        migrations.AddField(
            model_name="proformainvoiceline",
            name="item_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Product code / style ref, e.g. V181-0-02A",
                max_length=100,
            ),
        ),
    ]
