# Generated by Django 5.0.3 on 2026-06-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_pi_port_of_loading_inco_terms_item_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerpo",
            name="inco_terms",
            field=models.CharField(
                blank=True, default="", help_text="e.g. FOB NHAVA SHEVA", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="buyerpo",
            name="port_of_discharge",
            field=models.CharField(
                blank=True, default="", help_text="e.g. KHIDIRPUR PORT", max_length=400
            ),
        ),
        migrations.AddField(
            model_name="buyerpo",
            name="port_of_loading",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. NHAVA SHEVA PORT",
                max_length=400,
            ),
        ),
    ]
