# Generated by Django 5.0.3 on 2026-06-18 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_buyerpo_port_inco_terms"),
        ("procurement", "0003_remove_purchaseorder_intent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemIndentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(db_index=True, max_length=300, unique=True),
                ),
                ("fabric_lines", models.JSONField(blank=True, default=list)),
                ("trim_lines", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item Indent Template",
                "verbose_name_plural": "Item Indent Templates",
            },
        ),
        migrations.CreateModel(
            name="TrimMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 5 CM WIDE Reflective Tape D6101",
                        max_length=300,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Tape, Button, Velcro, Label, Thread",
                        max_length=100,
                    ),
                ),
                (
                    "default_unit",
                    models.CharField(
                        default="PCS", help_text="e.g. MTR, PCS, CONE", max_length=20
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trim Master",
                "verbose_name_plural": "Trims Library",
                "ordering": ["category", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="intentline",
            name="intent",
        ),
        migrations.RemoveField(
            model_name="intentsheet",
            name="intent",
        ),
        migrations.RemoveField(
            model_name="intentattachment",
            name="intent",
        ),
        migrations.RemoveField(
            model_name="intentattachment",
            name="uploaded_by",
        ),
        migrations.AlterUniqueTogether(
            name="intentline",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="intentline",
            name="inventory_item",
        ),
        migrations.RemoveField(
            model_name="intentline",
            name="sheet",
        ),
        migrations.RemoveField(
            model_name="planningsheet",
            name="pi",
        ),
        migrations.CreateModel(
            name="Indent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indent_number",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("indent_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("CONFIRMED", "Confirmed")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("pcs_per_carton", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "carton_ply",
                    models.CharField(
                        blank=True, default="", help_text="e.g. 5 PLY", max_length=50
                    ),
                ),
                (
                    "carton_dimensions",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 24.5*14.5*9 (L*W*H)",
                        max_length=100,
                    ),
                ),
                (
                    "prepared_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "received_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_indents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indents",
                        to="orders.proformainvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indent",
                "verbose_name_plural": "Indents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndentFabricLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(max_length=500)),
                ("color", models.CharField(blank=True, default="", max_length=120)),
                (
                    "consumption_per_pc",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("unit", models.CharField(default="MTRS", max_length=20)),
                (
                    "total_consumption",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "indent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabric_lines",
                        to="orders.indent",
                    ),
                ),
            ],
            options={
                "ordering": ["indent", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="IndentTrimLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trim_name", models.CharField(max_length=300)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                (
                    "color_variant",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Orange, GREY, Hi Vis Yellow",
                        max_length=120,
                    ),
                ),
                (
                    "size_variant",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 6.5 inch, 7 inch",
                        max_length=100,
                    ),
                ),
                (
                    "consumption_per_pc",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("unit", models.CharField(default="PCS", max_length=20)),
                (
                    "total_consumption",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("total_unit", models.CharField(blank=True, default="", max_length=20)),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. in stock",
                        max_length=200,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "indent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trim_lines",
                        to="orders.indent",
                    ),
                ),
                (
                    "trim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indent_lines",
                        to="orders.trimmaster",
                    ),
                ),
            ],
            options={
                "ordering": ["indent", "sort_order", "id"],
            },
        ),
        migrations.DeleteModel(
            name="Intent",
        ),
        migrations.DeleteModel(
            name="IntentAttachment",
        ),
        migrations.DeleteModel(
            name="IntentLine",
        ),
        migrations.DeleteModel(
            name="IntentSheet",
        ),
        migrations.DeleteModel(
            name="PlanningSheet",
        ),
    ]
