# Generated by Django 5.0.3 on 2026-06-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_itemindenttemplate_trimmaster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indent",
            name="selected_pi_line_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="PI line IDs included in this indent",
            ),
        ),
        migrations.AddField(
            model_name="indenttrimline",
            name="property_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Values for trim properties, e.g. {"Width": "5", "Color": "Orange"}',
            ),
        ),
        migrations.AddField(
            model_name="trimmaster",
            name="properties",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Configurable properties: [{"name": "Width", "unit": "CM"}, {"name": "Color", "unit": ""}]',
            ),
        ),
    ]
