# Generated by Django 5.0.3 on 2026-06-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_indent_selected_pi_line_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indentfabricline",
            name="roll_width",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional width of the fabric roll, e.g. 58 inch",
                max_length=50,
            ),
        ),
    ]
