# Generated by Django 5.0.3 on 2026-06-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_indent_fabric_roll_width"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trimmaster",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred supplier for this trim",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trims",
                to="suppliers.supplier",
            ),
        ),
    ]
