# Generated by Django 5.0.3 on 2026-06-21 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_contacts_shared_code"),
        ("orders", "0017_trimmaster_hsn_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_ref",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Sales / commercial invoice number", max_length=80
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "sale_date",
                    models.DateField(help_text="Dispatch / ex-factory / invoice date"),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payment_terms", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("PARTIAL", "Partially Received"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_po",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_entries",
                        to="orders.buyerpo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sales_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_entries",
                        to="customers.customer",
                    ),
                ),
                (
                    "pi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_entries",
                        to="orders.proformainvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Entry",
                "verbose_name_plural": "Sales Entries",
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField(default=1)),
                ("item_code", models.CharField(blank=True, default="", max_length=100)),
                ("item_name", models.CharField(blank=True, default="", max_length=300)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unit", models.CharField(blank=True, default="PCS", max_length=20)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "buyer_po_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_lines",
                        to="orders.buyerpoline",
                    ),
                ),
                (
                    "sales_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.salesentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Entry Line",
                "verbose_name_plural": "Sales Entry Lines",
                "ordering": ["serial_no", "id"],
            },
        ),
    ]
