# Generated by Django 5.0.3 on 2026-07-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_indent_carton_dimensions_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="indenttrimline",
            name="parts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Optional multi-part consumption breakdown for trims made of several components sharing one colour/qty basis, e.g. Velcro Hook & Loop: [{"label": "Hook", "consumption_per_pc": "0.28", "unit": "MTRS", "total_consumption": "1124.2", "total_unit": "MTRS"}, {"label": "Loop", ...}]',
            ),
        ),
    ]
