# Generated by Django 5.0.3 on 2026-07-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_indenttrimline_parts"),
    ]

    operations = [
        migrations.AddField(
            model_name="indent",
            name="carton_boxes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Multiple carton size rows, e.g. [{"pcs_per_carton": 12, "carton_ply": "5 PLY", "carton_dimensions": "24.5*14.5*9", "carton_dimensions_unit": "CMS"}]',
            ),
        ),
    ]
