# Generated by Django 5.0.3 on 2026-07-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_indent_carton_boxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="trimmaster",
            name="default_property_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Default values for properties, e.g. {"PLY": "5 PLY", "Dimensions": "24.5*14.5*9"}',
            ),
        ),
    ]
