# Generated by Django 5.0.3 on 2026-07-22 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_contacts_shared_code"),
        ("orders", "0025_uppercase_trim_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerpo",
            name="ship_to_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="buyerpo",
            name="ship_to_customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Ship-to entity (must share customer_code with Bill To customer when set)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ship_to_buyer_pos",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="buyerpo",
            name="ship_to_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
