# Generated by Django 5.0.3 on 2026-04-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        help_text="Legal name on documents", max_length=255
                    ),
                ),
                (
                    "trading_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short line under legal name on PDF letterhead",
                        max_length=200,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                (
                    "region_state",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("country", models.CharField(blank=True, default="", max_length=120)),
                ("phone", models.CharField(blank=True, default="", max_length=60)),
                ("fax", models.CharField(blank=True, default="", max_length=60)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "tax_registration",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="GST / VAT / EIN / CIN — printed on PDF header",
                        max_length=120,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company/logo/"),
                ),
                (
                    "watermark_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Diagonal watermark on every PDF page; defaults to legal name if empty",
                        max_length=64,
                    ),
                ),
                (
                    "pdf_footer_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Footer line on every PDF (e.g. registered office, jurisdiction)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company profile",
                "verbose_name_plural": "Company profile",
            },
        ),
    ]
