# Generated by Django 5.0.3 on 2026-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="pi_ref_prefix",
            field=models.CharField(
                blank=True,
                default="JBI",
                help_text="Short prefix for PI reference numbers, e.g. JBI → JBI/26-27/1",
                max_length=20,
            ),
        ),
    ]
