# Generated by Django 5.0.3 on 2026-06-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_pi_ref_prefix"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyCurrencyBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        db_index=True,
                        help_text="3-letter ISO currency code, e.g. USD",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "intermediary_bank_details",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Correspondent / intermediary bank for this currency — printed on PI",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency bank",
                "verbose_name_plural": "Currency banks",
                "ordering": ["currency"],
            },
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="our_bank_details",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Primary company bank — printed on all PIs (e.g. Punjab National Bank details)",
            ),
        ),
    ]
