# Generated by Django 5.0.3 on 2026-04-16 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("company_legal_name", models.CharField(max_length=255)),
                (
                    "trading_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Country or territory (any format)", max_length=120
                    ),
                ),
                (
                    "region_state",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=32, null=True)),
                ("address_line1", models.TextField(blank=True, null=True)),
                ("address_line2", models.TextField(blank=True, null=True)),
                (
                    "primary_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "secondary_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("mobile", models.CharField(blank=True, max_length=40, null=True)),
                ("fax", models.CharField(blank=True, max_length=40, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "tax_id_vat",
                    models.CharField(
                        blank=True,
                        help_text="VAT, GST, EIN, or other tax identifier",
                        max_length=80,
                        null=True,
                    ),
                ),
                ("default_currency", models.CharField(default="USD", max_length=3)),
                ("preferred_language", models.CharField(default="en", max_length=16)),
                (
                    "incoterms_default",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("payment_terms_default", models.TextField(blank=True, null=True)),
                ("bank_details", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["company_legal_name"],
            },
        ),
    ]
