# Generated by Django 5.0.3 on 2026-04-15 03:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BUTTON", "Button"),
                            ("THREAD", "Thread"),
                            ("ZIPPER", "Zipper"),
                            ("TAPE", "Tape"),
                            ("POLYBAG", "Polybag"),
                            ("FABRIC", "Fabric"),
                            ("LABEL", "Label"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("finish", models.CharField(blank=True, max_length=100, null=True)),
                ("material", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PCS", "Pieces"),
                            ("MTR", "Meters"),
                            ("KG", "Kilograms"),
                            ("ROLL", "Roll"),
                            ("BOX", "Box"),
                            ("SET", "Set"),
                        ],
                        default="PCS",
                        max_length=10,
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ORDER", "Ordered"),
                            ("RECEIVE", "Received"),
                            ("ISSUE", "Issued to Production"),
                            ("ADJUST", "Adjustment"),
                            ("RETURN", "Return"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vendor_supplier",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("stock_before", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Log",
                "verbose_name_plural": "Inventory Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
