# Generated by Django 5.0.3 on 2026-07-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventoryitem_trim_spec_lines"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylog",
            name="transaction_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
