# Generated by Django 5.0.3 on 2026-04-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_intent_intentattachment_intentline"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="purchaseorderitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="intent",
            field=models.ForeignKey(
                blank=True,
                help_text="Indent this PO fulfills (optional; can still set PI separately)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="orders.intent",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="intent_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Links this PO line to an intent BOM line for split qty across suppliers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_items",
                to="orders.intentline",
            ),
        ),
    ]
