# Generated by Django 5.0.3 on 2026-06-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_alter_purchaseorderitem_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="intent",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="intent_line",
        ),
    ]
