# Generated by Django 5.0.3 on 2026-06-21 12:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_trimmaster_hsn_code"),
        ("procurement", "0004_supplier_po_fields"),
        ("suppliers", "0002_supplier_contact_and_tax_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorderitem",
            options={
                "ordering": ["serial_no", "id"],
                "verbose_name": "Purchase Order Item",
                "verbose_name_plural": "Purchase Order Items",
            },
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="reference_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Buyer PO reference number for display",
                max_length=120,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_ref",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "bill_number",
                    models.CharField(
                        help_text="Supplier's invoice / bill number", max_length=80
                    ),
                ),
                ("supplier_name", models.CharField(max_length=200)),
                ("bill_date", models.DateField()),
                (
                    "received_date",
                    models.DateField(
                        blank=True,
                        help_text="Date material was received from supplier",
                        null=True,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "payment_terms",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_mode",
                    models.CharField(
                        choices=[("CGST_SGST", "CGST + SGST"), ("IGST", "IGST")],
                        default="CGST_SGST",
                        max_length=12,
                    ),
                ),
                (
                    "cgst_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sgst_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "igst_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchase_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="procurement.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_bills",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Bill",
                "verbose_name_plural": "Purchase Bills",
                "ordering": ["-bill_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseBillLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField(default=1)),
                (
                    "particulars",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("hsn_code", models.CharField(blank=True, default="", max_length=20)),
                (
                    "quantity_billed",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unit", models.CharField(blank=True, default="PCS", max_length=20)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.purchasebill",
                    ),
                ),
                (
                    "po_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_lines",
                        to="procurement.purchaseorderitem",
                    ),
                ),
                (
                    "trim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_lines",
                        to="orders.trimmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Bill Line",
                "verbose_name_plural": "Purchase Bill Lines",
                "ordering": ["serial_no", "id"],
            },
        ),
    ]
