# Generated by Django 5.0.3 on 2026-06-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0005_purchase_bill_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="transport_paid_by",
            field=models.CharField(
                blank=True,
                choices=[("SUPPLIER", "Supplier"), ("BUYER", "Buyer")],
                default="",
                help_text="Who bears transport / freight cost for this purchase order",
                max_length=20,
            ),
        ),
    ]
