# Generated by Django 5.0.3 on 2026-08-10 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_indenttrimline_supplier"),
        ("production", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuttingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cutting_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("cutting_date", models.DateField()),
                ("item_code", models.CharField(blank=True, default="", max_length=100)),
                ("item_name", models.CharField(blank=True, default="", max_length=300)),
                ("fabric", models.CharField(blank=True, default="", max_length=500)),
                ("color", models.CharField(blank=True, default="", max_length=120)),
                (
                    "roll_numbers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Roll numbers used for this cut, e.g. ["R-101", "R-102"]',
                    ),
                ),
                (
                    "size_breakdown",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Cut quantities by size: [{"size": "M", "qty": 120}]',
                    ),
                ),
                (
                    "consumption_per_pc",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Fabric consumption per pc from indent (or manual override)",
                        max_digits=10,
                    ),
                ),
                ("consumption_unit", models.CharField(default="MTRS", max_length=20)),
                ("total_pcs", models.PositiveIntegerField(default=0)),
                (
                    "total_consumption",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("RECORDED", "Recorded"), ("CANCELLED", "Cancelled")],
                        default="RECORDED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cutting_records",
                        to="orders.buyerpo",
                    ),
                ),
                (
                    "buyer_po_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cutting_records",
                        to="orders.buyerpoline",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cuttings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cutting_records",
                        to="orders.proformainvoice",
                    ),
                ),
                (
                    "pi_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cutting_records",
                        to="orders.proformainvoiceline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutting Record",
                "verbose_name_plural": "Cutting Records",
                "ordering": ["-cutting_date", "-created_at"],
            },
        ),
    ]
