# Generated by Django 5.0.3 on 2026-08-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_cutting_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuttingrecord",
            name="roll_width",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fabric roll width from indent, e.g. 58 inch",
                max_length=50,
            ),
        ),
    ]
