# Generated by Django 5.0.3 on 2026-08-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_cutting_roll_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuttingrecord",
            name="ideal_consumption",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Theoretical fabric use: consumption_per_pc × total_pcs",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="cuttingrecord",
            name="roll_numbers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Rolls used: [{"roll_no": "R-101", "total_meters": "120", "used_meters": "45.5"}]',
            ),
        ),
        migrations.AlterField(
            model_name="cuttingrecord",
            name="total_consumption",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Actual fabric used: sum of roll used_meters",
                max_digits=14,
            ),
        ),
    ]
